//
//  GamesShareView.swift
//  BaseballTracker
//
//  Created by Michael Peters on 3/14/25.
//

import SwiftUI

struct GamesShareView: View {
    
    // MARK: AppStorage variables
    @AppStorage("selectedColorScheme") private var selectedColorScheme = "System"
    @AppStorage("globalTeamName") private var globalTeamName = "My Team Name"
    
    // MARK: Other variables
    @Bindable var game: modelGame
    
    // MARK: Body
    var body: some View {
        
        // MARK: Calculated variables
        let gameOpponentString = $game.gameOpponent.wrappedValue == "" ? "Opponent" : $game.gameOpponent.wrappedValue
        
        let myTeam = !globalTeamName.isEmpty ? globalTeamName : "My Team Name"
        let opponentTeam = !game.gameOpponent.isEmpty ? game.gameOpponent : "<Enter Opponent Above>"
        
        let awayTeam = game.gameHomeAwaySelectedIndex == 0 ? myTeam : opponentTeam
        let homeTeam = game.gameHomeAwaySelectedIndex == 0 ? opponentTeam : myTeam
        
        VStack {
            BaseballRepeatView()
            Text("\(game.gameAtVersusString)\(gameOpponentString)")
                .font(.title).bold()
                .padding(.top, 10)
            HStack {
                Image(systemName: "baseball")
                Text(game.gameWinLossString)
                    .bold()
                Image(systemName: "baseball")
            }
            .font(.system(size: 50))
            .padding(.bottom, 10)
            Divider()
            LabeledContent("Date:", value: "[\(game.gameDate.getDayOfWeek())] - \(game.gameDate.formatDate())")
            Divider()
            LabeledContent("Home/Away:", value: arrGameHomeAway[game.gameHomeAwaySelectedIndex].text)
            Divider()
            Text("Scoreboard:")
            LabeledContent(awayTeam, value: game.gameAwayScore)
            LabeledContent(homeTeam, value: game.gameHomeScore)
            Divider()
            Group {
                Text("Screenshot generated by:")
                    .padding(.top, 5)
                Text(Constants.appName)
                    .padding(.bottom, 5)
            }
            .font(.caption2)
            .foregroundColor(.secondary)
            BaseballRepeatView()
        }
        .padding()
        .frame(width: 350, height: 400)
        .background(RoundedRectangle(cornerRadius: 10)
            .fill(Color(.systemBackground)))
        .overlay {
            RoundedRectangle(cornerRadius: 10).stroke(lineWidth: 2)
        }
        .preferredColorScheme(selectedColorScheme == "System" ? nil : selectedColorScheme == "Dark" ? .dark : .light)
    }
}

// MARK: Preview
#Preview {
    GamesShareView(game: .init(
        gameHomeAwaySelectedIndex: 0,
        gameDate: .now,
        gameOpponent: "Opponent",
        gameAwayScore: "5",
        gameHomeScore: "10",
        gameWinLossString: "Win",
        gameAtVersusString: "@")
    )
}
